### ISSUE TITLE
[Suggestion] BUTTON MAPPING

### ISSUE THREAD

**Issue by Cristian101400** [masterfeizz/DaedalusX64-3DS#26] opened 2020-05-11 01:54 UTC
Button mapping should be added. Give us some more options to tinker with aswell.

**Comment by L-i-n-u-x-C-a-t** [comment] 2020-05-11 07:11
Duplicate of #22

**Comment by masterfeizz** [comment] 2020-05-11 11:59
Duplicate

**Closed** 2020-05-11 11:59 UTC
