### ISSUE TITLE
[Feature Request] Control settings

### ISSUE THREAD

**Issue by MuPlayZZ** [masterfeizz/DaedalusX64-3DS#41] opened 2020-05-18 12:04 UTC
When you open daedelusx64, there should be an options menu that lets you change the controls.

**Comment by L-i-n-u-x-C-a-t** [comment] 2020-05-18 14:33
duplicate of #22. Please read the existing issues before referencing one, this is the 4th duplicate already.

**Closed** 2020-05-25 18:54 UTC
